### ISSUE TITLE
Is there a meaningful difference between this and git-subrepo?

### ISSUE THREAD

**Issue by jawshooah** [tdd/git-stree#18]
This project appears to share a lot with @ingydotnet's [git-subrepo](https://github.com/ingydotnet/git-subrepo) in terms of goals and methodology. Both are fairly recent, and appear to be significantly more useful than git-submodule and git-subtree, though git-subrepo got the jump on you by about a year.

Since you presumably started this project out of frustration with existing solutions, could you give a little context as to what sets git-stree apart? I'm getting fed up with submodules myself, and am looking for a more sustainable setup. Thanks!

**Comment by tdd** [comment]
Hey Josh,

Woah.  Woah, woah.  I wasn't even aware of git-subrepo: never showed up on my radar when I was tackling these issues.

It's definitely way more "complete" than git-stree, codewise…  It does a metric ton of things, and the code is way more involved: Bash+, full TAP-based test suite, man page, etc.  It's very impressive work. It also relies on in-code settings files (the `.gitsubrepo` files), which certainly works around the pitfall of local configs.

Installation still leaves a lot to be desired (cloning and sourcing by hand, instead of regular distrib channels), but it does the job still, and I'm not any further myself at this point.

OTOH, it doesn't quite fit my own needs. In particular, it doesn't let you backport (push) specific local commits instead of the whole detected series.  But it would undoubtedly be trivial to add.

Honestly, I'm kinda bummed to discover that project this late; had I seen it earlier, I'd probably have joined forces and added alternative behaviors instead of writing my own. Still, my own code does less, and is waaaaaaay smaller. Not an advantage at all, UX-wise, but I like being able to figure my whole code out in less than a few hours (so far).

It does seem like git-subrepo is a much better choice right now. Ingy's obviously working hard on it, and the current state of code/feature/test maturity is much farther along than here. I'll def explore his codebase more in the coming days and grab the good ideas and infrastructure (e.g. testing harness) from it.

I need to dive into the inner workings of his code, though; because if they match my own taste enough, wrt used Git commands, I might well just switch and augment his stuff.

**Comment by ingydotnet** [comment]
@jawshooah @tdd Feel free to stop by #git-commands on irc.freenode.net if you'd like to chat.

Cheers, Ingy
