### ISSUE TITLE
Submodules?

### ISSUE THREAD

**Issue by d12frosted** [tdd/git-stree#31]
Hey, I have a question about strees that contain submodules. Is it possible somehow to load submodules? Because when I do `git submodule update --init` I get 

```
No submodule mapping found in .gitmodules for path 'vendor/spacemacs/spacemacs/extensions/revive'
```

(this is for the repository I am using in #30 )

**Comment by tdd** [comment]
Hey there!

Woah, submodules in subtrees. Looks like you're summoning Zalgo there.

This is tough, as submodules are handled at their container repo's root directory level. Therefore it would expect a `.gitmodules` at the root of your container repo, which doesn't happen: it's at the subtree root's dir. But because this is a subtree, not a submodule, it doesn't qualify as a *repo root dir*. So the mix-and-match is difficult.

I would advise against this particular blend :confused:

**Comment by d12frosted** [comment]
> Looks like you're summoning Zalgo there.

Haha, right. 

Thanks for explanations. :)

> I would advise against this particular blend :confused:

Yeah, I thought so.
